### ISSUE TITLE
Task never finished

### ISSUE THREAD

**Issue by ghost** [daimajia/java-multithread-downloader#2]
``` java
while(!mission.isFinished()) {
    System.out.println((mission.getDownloadedSize() / 1024) + " " +            mission.getReadableSpeed());
}
```

I have simple loop that waits when file will be downloaded and show user download status, but this loop never ends.

**Comment by daimajia** [comment]
I'm so sorry for the bugs...

I' ll reconstruct this project .. wait me some days.

**Comment by ghost** [comment]
Okey ^_^ With your lib download speed increased from 300kbs-600kbs to 1.2mb-3mb.

**Comment by daimajia** [comment]
Thank you , i'm so happy to hear this~

**Comment by ghost** [comment]
Zzzzz

**Comment by ghost** [comment]
Zzzz....

**Comment by daimajia** [comment]
what 's up?

**Comment by ghost** [comment]
Waiting your lib =D

**Comment by daimajia** [comment]
I am so sorry ~ 

little busy recently~ are u harry to use this lib ?

**Comment by ghost** [comment]
No, i have about 20 days.

**Comment by daimajia** [comment]
is this your task or homework?

**Comment by ghost** [comment]
I working on new launcher for my server. Well, if you are busy, i will found other solution.
